# Generated by Django 4.2.9 on 2024-03-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bodey',
            new_name='body',
        ),
    ]
